on:
  pull_request:
    branches: [ main ]
name: Run Samples
jobs:
  samples:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run sample application
        working-directory: ./samples
        run: go run run_sample.go
      - name: Run snippets
        working-directory: ./samples
        run: |
          for filename in snippets/*.go; do
            name=${filename##*/}
            base=${name%.go}
            echo "Running sample $base"
            go run run_sample.go "$base" || ! break
          done
